/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteQuestionarieInterpretationArgs } from "./DeleteQuestionarieInterpretationArgs";
import { QuestionarieInterpretationFindManyArgs } from "./QuestionarieInterpretationFindManyArgs";
import { QuestionarieInterpretationFindUniqueArgs } from "./QuestionarieInterpretationFindUniqueArgs";
import { QuestionarieInterpretation } from "./QuestionarieInterpretation";
import { QuestionarieInterpretationService } from "../questionarieInterpretation.service";

@graphql.Resolver(() => QuestionarieInterpretation)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class QuestionarieInterpretationResolverBase {
  constructor(
    protected readonly service: QuestionarieInterpretationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "QuestionarieInterpretation",
    action: "read",
    possession: "any",
  })
  async _questionarieInterpretationsMeta(
    @graphql.Args() args: QuestionarieInterpretationFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [QuestionarieInterpretation])
  @nestAccessControl.UseRoles({
    resource: "QuestionarieInterpretation",
    action: "read",
    possession: "any",
  })
  async questionarieInterpretations(
    @graphql.Args() args: QuestionarieInterpretationFindManyArgs
  ): Promise<QuestionarieInterpretation[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => QuestionarieInterpretation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "QuestionarieInterpretation",
    action: "read",
    possession: "own",
  })
  async questionarieInterpretation(
    @graphql.Args() args: QuestionarieInterpretationFindUniqueArgs
  ): Promise<QuestionarieInterpretation | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => QuestionarieInterpretation)
  @nestAccessControl.UseRoles({
    resource: "QuestionarieInterpretation",
    action: "delete",
    possession: "any",
  })
  async deleteQuestionarieInterpretation(
    @graphql.Args() args: DeleteQuestionarieInterpretationArgs
  ): Promise<QuestionarieInterpretation | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
