/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsOptional,
  IsString,
  IsInt,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { PaymentWhereUniqueInput } from "../../payment/base/PaymentWhereUniqueInput";
import { PaymentCreateNestedManyWithoutSessionsInput } from "./PaymentCreateNestedManyWithoutSessionsInput";
import { EnumSessionPayStatus } from "./EnumSessionPayStatus";
import { PsychotherapistWhereUniqueInput } from "../../psychotherapist/base/PsychotherapistWhereUniqueInput";
import { PsychoScheduleWhereUniqueInput } from "../../psychoSchedule/base/PsychoScheduleWhereUniqueInput";
import { ReportWhereUniqueInput } from "../../report/base/ReportWhereUniqueInput";
import { EnumSessionSessionType } from "./EnumSessionSessionType";
import { EnumSessionStatus } from "./EnumSessionStatus";
@InputType()
class SessionCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  attendTime?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  desc?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  length?: number | null;

  @ApiProperty({
    required: false,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @IsOptional()
  @Field(() => PatientWhereUniqueInput, {
    nullable: true,
  })
  patientId?: PatientWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PaymentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PaymentWhereUniqueInput)
  @IsOptional()
  @Field(() => PaymentWhereUniqueInput, {
    nullable: true,
  })
  payId?: PaymentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutSessionsInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutSessionsInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutSessionsInput, {
    nullable: true,
  })
  payments?: PaymentCreateNestedManyWithoutSessionsInput;

  @ApiProperty({
    required: false,
    enum: EnumSessionPayStatus,
  })
  @IsEnum(EnumSessionPayStatus)
  @IsOptional()
  @Field(() => EnumSessionPayStatus, {
    nullable: true,
  })
  payStatus?: "UnPaid" | "FullyPaid" | "PartailPaid" | null;

  @ApiProperty({
    required: false,
    type: () => PsychotherapistWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PsychotherapistWhereUniqueInput)
  @IsOptional()
  @Field(() => PsychotherapistWhereUniqueInput, {
    nullable: true,
  })
  psychoId?: PsychotherapistWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PsychoScheduleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PsychoScheduleWhereUniqueInput)
  @IsOptional()
  @Field(() => PsychoScheduleWhereUniqueInput, {
    nullable: true,
  })
  psychoScheduleId?: PsychoScheduleWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReportWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ReportWhereUniqueInput)
  @IsOptional()
  @Field(() => ReportWhereUniqueInput, {
    nullable: true,
  })
  reportId?: ReportWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumSessionSessionType,
  })
  @IsEnum(EnumSessionSessionType)
  @IsOptional()
  @Field(() => EnumSessionSessionType, {
    nullable: true,
  })
  sessionType?: "Online" | "Offline" | "Mix" | null;

  @ApiProperty({
    required: false,
    enum: EnumSessionStatus,
  })
  @IsEnum(EnumSessionStatus)
  @IsOptional()
  @Field(() => EnumSessionStatus, {
    nullable: true,
  })
  status?: "Free" | "Reserved" | "FinalChecked" | "InProgress" | "Done" | null;
}
export { SessionCreateInput };
