/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WaitingListService } from "../waitingList.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WaitingListCreateInput } from "./WaitingListCreateInput";
import { WaitingListWhereInput } from "./WaitingListWhereInput";
import { WaitingListWhereUniqueInput } from "./WaitingListWhereUniqueInput";
import { WaitingListFindManyArgs } from "./WaitingListFindManyArgs";
import { WaitingListUpdateInput } from "./WaitingListUpdateInput";
import { WaitingList } from "./WaitingList";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WaitingListControllerBase {
  constructor(
    protected readonly service: WaitingListService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "WaitingList",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WaitingList })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: WaitingListCreateInput
  ): Promise<WaitingList> {
    return await this.service.create({
      data: {
        ...data,

        psychoId: data.psychoId
          ? {
              connect: data.psychoId,
            }
          : undefined,
      },
      select: {
        callCounts: true,
        createdAt: true,
        id: true,
        isEmergency: true,
        isFirstSession: true,
        lastRequestTime: true,
        patientId: true,
        priority: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "WaitingList",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [WaitingList] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(WaitingListFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<WaitingList[]> {
    const args = plainToClass(WaitingListFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        callCounts: true,
        createdAt: true,
        id: true,
        isEmergency: true,
        isFirstSession: true,
        lastRequestTime: true,
        patientId: true,
        priority: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "WaitingList",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WaitingList })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: WaitingListWhereUniqueInput
  ): Promise<WaitingList | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        callCounts: true,
        createdAt: true,
        id: true,
        isEmergency: true,
        isFirstSession: true,
        lastRequestTime: true,
        patientId: true,
        priority: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "WaitingList",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WaitingList })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: WaitingListWhereUniqueInput,
    @common.Body() data: WaitingListUpdateInput
  ): Promise<WaitingList | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          psychoId: data.psychoId
            ? {
                connect: data.psychoId,
              }
            : undefined,
        },
        select: {
          callCounts: true,
          createdAt: true,
          id: true,
          isEmergency: true,
          isFirstSession: true,
          lastRequestTime: true,
          patientId: true,
          priority: true,

          psychoId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "WaitingList",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WaitingList })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: WaitingListWhereUniqueInput
  ): Promise<WaitingList | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          callCounts: true,
          createdAt: true,
          id: true,
          isEmergency: true,
          isFirstSession: true,
          lastRequestTime: true,
          patientId: true,
          priority: true,

          psychoId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
