/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CheckoutPaymentService } from "../checkoutPayment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CheckoutPaymentCreateInput } from "./CheckoutPaymentCreateInput";
import { CheckoutPaymentWhereInput } from "./CheckoutPaymentWhereInput";
import { CheckoutPaymentWhereUniqueInput } from "./CheckoutPaymentWhereUniqueInput";
import { CheckoutPaymentFindManyArgs } from "./CheckoutPaymentFindManyArgs";
import { CheckoutPaymentUpdateInput } from "./CheckoutPaymentUpdateInput";
import { CheckoutPayment } from "./CheckoutPayment";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CheckoutPaymentControllerBase {
  constructor(
    protected readonly service: CheckoutPaymentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CheckoutPayment",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CheckoutPayment })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: CheckoutPaymentCreateInput
  ): Promise<CheckoutPayment> {
    return await this.service.create({
      data: {
        ...data,

        psychoId: data.psychoId
          ? {
              connect: data.psychoId,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        id: true,
        month: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        resloveDate: true,
        resolved: true,
        updatedAt: true,
        year: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CheckoutPayment",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [CheckoutPayment] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(CheckoutPaymentFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<CheckoutPayment[]> {
    const args = plainToClass(CheckoutPaymentFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        month: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        resloveDate: true,
        resolved: true,
        updatedAt: true,
        year: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CheckoutPayment",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CheckoutPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CheckoutPaymentWhereUniqueInput
  ): Promise<CheckoutPayment | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        id: true,
        month: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        resloveDate: true,
        resolved: true,
        updatedAt: true,
        year: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "CheckoutPayment",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CheckoutPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CheckoutPaymentWhereUniqueInput,
    @common.Body() data: CheckoutPaymentUpdateInput
  ): Promise<CheckoutPayment | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          psychoId: data.psychoId
            ? {
                connect: data.psychoId,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          id: true,
          month: true,

          psychoId: {
            select: {
              id: true,
            },
          },

          resloveDate: true,
          resolved: true,
          updatedAt: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "CheckoutPayment",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CheckoutPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CheckoutPaymentWhereUniqueInput
  ): Promise<CheckoutPayment | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          id: true,
          month: true,

          psychoId: {
            select: {
              id: true,
            },
          },

          resloveDate: true,
          resolved: true,
          updatedAt: true,
          year: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
