/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PsychotherapistService } from "../psychotherapist.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PsychotherapistCreateInput } from "./PsychotherapistCreateInput";
import { PsychotherapistWhereInput } from "./PsychotherapistWhereInput";
import { PsychotherapistWhereUniqueInput } from "./PsychotherapistWhereUniqueInput";
import { PsychotherapistFindManyArgs } from "./PsychotherapistFindManyArgs";
import { PsychotherapistUpdateInput } from "./PsychotherapistUpdateInput";
import { Psychotherapist } from "./Psychotherapist";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PsychotherapistControllerBase {
  constructor(
    protected readonly service: PsychotherapistService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Psychotherapist",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Psychotherapist })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PsychotherapistCreateInput
  ): Promise<Psychotherapist> {
    return await this.service.create({
      data: data,
      select: {
        cardNumber: true,
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        pricePerHour: true,
        shabaNumber: true,
        totalSessionsCount: true,
        totalSessionsLength: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Psychotherapist",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Psychotherapist] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PsychotherapistFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Psychotherapist[]> {
    const args = plainToClass(PsychotherapistFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        cardNumber: true,
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        pricePerHour: true,
        shabaNumber: true,
        totalSessionsCount: true,
        totalSessionsLength: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Psychotherapist",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Psychotherapist })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PsychotherapistWhereUniqueInput
  ): Promise<Psychotherapist | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        cardNumber: true,
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        pricePerHour: true,
        shabaNumber: true,
        totalSessionsCount: true,
        totalSessionsLength: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Psychotherapist",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Psychotherapist })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PsychotherapistWhereUniqueInput,
    @common.Body() data: PsychotherapistUpdateInput
  ): Promise<Psychotherapist | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          cardNumber: true,
          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          pricePerHour: true,
          shabaNumber: true,
          totalSessionsCount: true,
          totalSessionsLength: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Psychotherapist",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Psychotherapist })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PsychotherapistWhereUniqueInput
  ): Promise<Psychotherapist | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          cardNumber: true,
          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          pricePerHour: true,
          shabaNumber: true,
          totalSessionsCount: true,
          totalSessionsLength: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
