/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PsychoScheduleService } from "../psychoSchedule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PsychoScheduleCreateInput } from "./PsychoScheduleCreateInput";
import { PsychoScheduleWhereInput } from "./PsychoScheduleWhereInput";
import { PsychoScheduleWhereUniqueInput } from "./PsychoScheduleWhereUniqueInput";
import { PsychoScheduleFindManyArgs } from "./PsychoScheduleFindManyArgs";
import { PsychoScheduleUpdateInput } from "./PsychoScheduleUpdateInput";
import { PsychoSchedule } from "./PsychoSchedule";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { SessionWhereUniqueInput } from "../../session/base/SessionWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PsychoScheduleControllerBase {
  constructor(
    protected readonly service: PsychoScheduleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PsychoSchedule })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: PsychoScheduleCreateInput
  ): Promise<PsychoSchedule> {
    return await this.service.create({
      data: {
        ...data,

        psychoId: data.psychoId
          ? {
              connect: data.psychoId,
            }
          : undefined,
      },
      select: {
        beginTime: true,
        createdAt: true,
        day: true,
        endTime: true,
        id: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [PsychoSchedule] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(PsychoScheduleFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<PsychoSchedule[]> {
    const args = plainToClass(PsychoScheduleFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        beginTime: true,
        createdAt: true,
        day: true,
        endTime: true,
        id: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PsychoSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: PsychoScheduleWhereUniqueInput
  ): Promise<PsychoSchedule | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        beginTime: true,
        createdAt: true,
        day: true,
        endTime: true,
        id: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PsychoSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: PsychoScheduleWhereUniqueInput,
    @common.Body() data: PsychoScheduleUpdateInput
  ): Promise<PsychoSchedule | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          psychoId: data.psychoId
            ? {
                connect: data.psychoId,
              }
            : undefined,
        },
        select: {
          beginTime: true,
          createdAt: true,
          day: true,
          endTime: true,
          id: true,

          psychoId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PsychoSchedule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: PsychoScheduleWhereUniqueInput
  ): Promise<PsychoSchedule | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          beginTime: true,
          createdAt: true,
          day: true,
          endTime: true,
          id: true,

          psychoId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Session",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/sessions")
  @ApiNestedQuery(SessionFindManyArgs)
  async findManySessions(
    @common.Req() request: Request,
    @common.Param() params: PsychoScheduleWhereUniqueInput
  ): Promise<Session[]> {
    const query = plainToClass(SessionFindManyArgs, request.query);
    const results = await this.service.findSessions(params.id, {
      ...query,
      select: {
        attendTime: true,
        createdAt: true,
        desc: true,
        id: true,
        length: true,

        patientId: {
          select: {
            id: true,
          },
        },

        payId: {
          select: {
            id: true,
          },
        },

        payStatus: true,

        psychoId: {
          select: {
            id: true,
          },
        },

        psychoScheduleId: {
          select: {
            id: true,
          },
        },

        reportId: {
          select: {
            id: true,
          },
        },

        sessionType: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/sessions")
  async connectSessions(
    @common.Param() params: PsychoScheduleWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/sessions")
  async updateSessions(
    @common.Param() params: PsychoScheduleWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "PsychoSchedule",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/sessions")
  async disconnectSessions(
    @common.Param() params: PsychoScheduleWhereUniqueInput,
    @common.Body() body: SessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sessions: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
